datadir : '/datadir'
chain : "dynamic-cdk"

zkevm.l2-chain-id: {{.l2_chain_id}}
zkevm.l2-sequencer-rpc-url: "{{.seq_rpc}}"
zkevm.l2-datastreamer-url: "{{.seq_ds}}"
zkevm.l2-datastreamer-timeout: "0s"

zkevm.l1-chain-id: {{.l1_chain_id}}
zkevm.l1-rpc-url: "{{.l1_rpc_url}}"
zkevm.l1-rollup-id: 1
zkevm.l1-first-block: {{.rollupBlockNumber}}
# zkevm.l1-first-block: 1
zkevm.l1-matic-contract-address: "{{.polAddress}}"
zkevm.l1-block-range: 20000
zkevm.l1-query-delay: 6000
zkevm.l1-highest-block-type: "latest"

zkevm.address-sequencer: "{{.sequencer.address}}"
zkevm.address-admin: "{{.admin.address}}"
zkevm.address-zkevm: "{{.zkevmAddress}}"
zkevm.address-rollup: "{{.rollupAddress}}"
zkevm.address-ger-manager: "{{.gerAddress}}"

zkevm.executor-strict: true
zkevm.executor-urls: "{{.stateless_executor}}:{{.executor_port}}"
zkevm.witness-full: false
zkevm.sequencer-block-seal-time: "3s"
zkevm.sequencer-batch-seal-time: "12s"
zkevm.allow-pre-eip155-transactions: true
zkevm.disable-virtual-counters: false

zkevm.default-gas-price: 1000000000
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.12

zkevm.rpc-ratelimit: 250
zkevm.data-stream-host: "127.0.0.1"
zkevm.data-stream-port: {{.sequencer_ds_port}}

externalcl: true
private.api.addr : "localhost:9096"

txpool.disable: false
txpool.globalslots: 30000
txpool.globalbasefeeslots: 30000
txpool.globalqueue: 30000
torrent.port: 42070

http : true
http.api : [eth, debug, net, trace, web3, erigon, txpool, zkevm]
http.addr: "0.0.0.0"
http.port: {{.sequencer_rpc_port}}
http.vhosts: '*'
http.corsdomain: '*'
ws: true
rpc.batch.limit: 500
zkevm.limbo: true
log.json: false
log.console.verbosity: “info”
debug.timers: true

