[Log]
Environment = "development"
Level = "info"
Outputs = ["stdout"]

[SequenceSender]
IsValidiumMode = {{.is_validium}}
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
L1BlockTimestampMargin = "120s"
MaxTxSizeForL1 = 131072
L2Coinbase =  "{{.sequencer.address}}"
PrivateKey = {Path = "/config/sequencer.keystore", Password = "{{.keystore_password}}"}
SequencesTxFileName = "/tmp/sequencesender.json"
GasOffset = 80000
WaitPeriodPurgeTxFile = "48h"
MaxPendingTx = 1
MaxBatchesForL1 = 300
SanityCheckRPCURL = "{{.l2_rpc_url}}"
	[SequenceSender.StreamClient]
		Server = "{{.ds_url}}"
	[SequenceSender.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "1s"
		PrivateKeys = [
			{Path = "/config/sequencer.keystore", Password = "{{.keystore_password}}"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "/tmp/ethtxmanager.json"
		ReadPendingL1Txs = false
		# For both: 0 mean disabled (safe and finalized)
		# Set to 1 for the min possible wait
		SafeStatusL1NumberOfBlocks = 1
		FinalizedStatusL1NumberOfBlocks = 1
			[SequenceSender.EthTxManager.Etherman]
				URL = "{{.l1_rpc_url}}"
				MultiGasProvider = false
				L1ChainID =  {{.l1_chain_id}}
				HTTPHeaders = []
